#!/bin/sh
#
# Demo to analyse a python module and print a summary
# of the functions, and classes it contains.
#
# make sire that the latest version of pyawk can be found
cp ../pyawk.py .

# run pyawk on itself
python3 pyawk.py -f analyse.scr pyawk.py
